#!/bin/sh

# A UI for detecting and selecting all displays.
# Probes xrandr for connected displays and lets user select one to use.
# User may also select "manual selection" which opens arandr.
# I plan on adding a routine from multi-monitor setups later.

twoscreen() { # If multi-monitor is selected and there are two screens.
	primary=$(echo "$screens" | dmenu -i -p "Display primário")
	secondary=$(echo "$screens" | grep -v "$primary")
	direction=$(printf "left\\nright" | dmenu -i -p "Em qual lado de $primary o display $secondary deve estar?")
	xrandr --output "$primary" --auto --output "$secondary" --"$direction"-of "$primary" --auto
	}

morescreen() { # If multi-monitor is selected and there are more than two screens.
	primary=$(echo "$screens" | dmenu -i -p "Primeiro Display:")
	secondary=$(echo "$screens" | grep -v "$primary" | dmenu -i -p "Segundo Display:")
	direction=$(printf "left\\nright" | dmenu -i -p "What side of $primary should $secondary be on?")
	tertiary=$(echo "$screens" | grep -v "$primary" | grep -v "$secondary" | dmenu -i -p "Terceiro Display:")
	xrandr --output "$primary" --auto --output "$secondary" --"$direction"-of "$primary" --auto --output "$tertiary" --"$(printf "left\\nright" | grep -v "$direction")"-of "$primary" --auto
	}

multimon() { # Multi-monitor handler.
	case "$(echo "$screens" | wc -l)" in
		1) xrandr $(echo "$allposs" | awk '{print "--output", $1, "--auto"}' | tr '\n' ' ') ;;
		2) twoscreen ;;
		*) morescreen ;;
	esac ;}

# Get all possible displays
# Pega podas as possibilidades de display
allposs=$(xrandr -q | grep "connected")

# Get all connected screens.
# Pega todos os monitores conectados
screens=$(echo "$allposs" | grep " connected" | awk '{print $1}')

# Get user choice including multi-monitor and manual selection:
# Pega escolha do usuário
chosen=$(printf "%s\\nMulti-monitor\\nSeleção Manual" "$screens" | dmenu -i -p "Selecionar Display:") &&
case "$chosen" in
	"Seleção Manual") arandr ; exit ;;
	"Multi-monitor") multimon ;;
	*) xrandr --output "$chosen" --auto $(echo "$screens" | grep -v "$chosen" | awk '{print "--output", $1, "--off"}' | tr '\n' ' ') ;;
esac

# Fix feh background if screen size/arangement has changed.
feh --bg-scale "$HOME/.config/wall.jpg"
# Polybar users will want to uncomment this line, which reactivates polybar on all new displays:
#polybar_launch
# Re-remap keys if keyboard added (for laptop bases)
#remaps
